[package]
name = "byte_coding"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["derive", "coder"]
derive = ["byte_coding_derive"]
coder = []

[dependencies]
byte_coding_derive = { path = "byte_coding_derive", optional = true }