[package]
name = "byte_coding_derive"
version = "0.4.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
# syn = { version = "1.0", features = ["default", "extra-traits"] }
quote = "1.0"

[dev-dependencies]
byte_coding = { path = "../", features = [] }